"""
Data Loading Utilities.
Uses centralized settings from src.config.settings.
"""

import pandas as pd
import streamlit as st

from src.config.settings import FileNames, Paths


@st.cache_data(ttl=3600, show_spinner=False)
def load_rainbow_predictions() -> pd.DataFrame | None:
    """Loads the final rainbow forecast predictions."""
    file_path = Paths.PREDICTIONS / FileNames.FORECAST_FINAL

    if not file_path.exists():
        return None

    try:
        df = pd.read_csv(file_path)
        if "fecha" in df.columns:
            df["fecha"] = pd.to_datetime(df["fecha"])
        return df
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return None


@st.cache_data(show_spinner=False)
def load_evaluation_data(filename: str) -> pd.DataFrame | None:
    file_path = Paths.PREDICTIONS / filename
    if file_path.exists():
        return pd.read_csv(file_path)
    return None


@st.cache_data
def load_validation_data():
    """Loads the validation dataset generated by pipeline 06."""
    path = Paths.PREDICTIONS_COMPARATION / FileNames.FORECAST_ONESTEP
    if not path.exists():
        return None

    df = pd.read_csv(path)
    df["fecha"] = pd.to_datetime(df["fecha"])
    return df


def apply_custom_css() -> None:
    """Applies custom CSS styles to the Streamlit app."""
    css_path = Paths.ASSETS / "style.css"
    if css_path.exists():
        with open(css_path, encoding="utf-8") as f:
            st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
